# Generated by Django 5.0.1 on 2024-07-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('telegram_users', '0001_initial'),
        ('types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('date_of_purchase', models.DateField()),
                ('validity_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shops')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types.types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_users.telegramusers')),
            ],
            options={
                'verbose_name': 'Guarantee',
                'verbose_name_plural': 'Guarantees',
            },
        ),
    ]
